"""
Signal History Logger & Time-Series Audit Hub.
Records and persists every signal ever generated by the system across
Sinyal BUY Institusional, BPJS (Beli Pagi Jual Sore), BSJP (Beli Sore Jual Pagi),
ORCA Big-Money, and Smart Pick Technical Rebounds with precise timestamps.
"""

from datetime import datetime, date, timedelta
from typing import List, Dict, Any, Optional
import json
import os
import threading

class SignalHistoryEngine:
    """
    Centralized Signal History Logger with Disk Persistence & Thread-Safe Appends.
    """

    HISTORY_FILE = os.path.join("data", "signal_history.json")
    _lock = threading.Lock()

    @classmethod
    def load_history(cls) -> List[Dict[str, Any]]:
        """Load full historical signal logs from disk."""
        if not os.path.exists(cls.HISTORY_FILE):
            return []
        try:
            with open(cls.HISTORY_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            return []

    @classmethod
    def save_history(cls, records: List[Dict[str, Any]]) -> None:
        """Save history records to disk."""
        os.makedirs(os.path.dirname(cls.HISTORY_FILE), exist_ok=True)
        with open(cls.HISTORY_FILE, "w", encoding="utf-8") as f:
            json.dump(records, f, indent=2, default=str)

    @classmethod
    def record_signal_event(
        cls,
        signal_type: str,  # "BUY_INSTITUSIONAL", "BPJS_PAGI", "BSJP_SORE", "ORCA_BUY", "SMART_PICK"
        symbol: str,
        name: str,
        sector: str,
        price_at_signal: float,
        ai_score: float,
        setup_pattern: str,
        entry_zone: str,
        target_tp1: str,
        stop_loss: str,
        target_tp2: Optional[str] = None,
        risk_reward: Optional[str] = None,
        safety_shield_status: str = "AMAN / BEBAS GORENGAN",
        rationale: str = "",
        timestamp: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Record a signal event with exact date, time, and execution parameters.
        Prevents duplicate entries for the same symbol and signal_type within the same session.
        """
        with cls._lock:
            history = cls.load_history()
            now = datetime.now()
            
            ts_full = timestamp or now.strftime("%Y-%m-%d %H:%M:%S WIB")
            date_str = now.strftime("%Y-%m-%d")
            time_str = now.strftime("%H:%M:%S WIB")

            # Check if this exact signal was already recorded today in the last 2 hours
            for item in history:
                if (
                    item.get("symbol") == symbol
                    and item.get("signal_type") == signal_type
                    and item.get("signal_date") == date_str
                ):
                    return item  # Already recorded

            new_id = len(history) + 1
            event = {
                "id": new_id,
                "timestamp": ts_full,
                "signal_date": date_str,
                "signal_time": time_str,
                "signal_type": signal_type,
                "symbol": symbol,
                "name": name,
                "sector": sector,
                "price_at_signal": float(price_at_signal),
                "ai_score": float(ai_score),
                "setup_pattern": setup_pattern,
                "entry_zone": entry_zone,
                "target_tp1": target_tp1,
                "target_tp2": target_tp2 or "-",
                "stop_loss": stop_loss,
                "risk_reward": risk_reward or "-",
                "safety_shield_status": safety_shield_status,
                "rationale": rationale
            }

            history.append(event)
            cls.save_history(history)
            return event

    @classmethod
    def get_history(
        cls,
        signal_type: Optional[str] = None,
        symbol: Optional[str] = None,
        date_from: Optional[str] = None,
        limit: int = 100
    ) -> List[Dict[str, Any]]:
        """
        Query signal history with filtering and descending chronological sorting.
        """
        history = cls.load_history()
        if not history:
            history = cls.seed_initial_history()

        filtered = history

        if signal_type and signal_type.upper() != "ALL":
            filtered = [h for h in filtered if h.get("signal_type", "").upper() == signal_type.upper()]

        if symbol and symbol.strip():
            sym_clean = symbol.upper().strip()
            filtered = [h for h in filtered if sym_clean in h.get("symbol", "").upper()]

        if date_from:
            filtered = [h for h in filtered if h.get("signal_date", "") >= date_from]

        # Sort newest first
        sorted_history = sorted(
            filtered,
            key=lambda x: (x.get("signal_date", ""), x.get("signal_time", ""), x.get("id", 0)),
            reverse=True
        )
        return sorted_history[:limit]

    @classmethod
    def seed_initial_history(cls) -> List[Dict[str, Any]]:
        """
        Populate real historical signal events from actual Yahoo Finance market bars.
        Zero dummy/mocked data.
        """
        existing = cls.load_history()
        if existing:
            return existing

        try:
            from src.analytics.real_data_miner import RealDataMiner
            evals, hists = RealDataMiner.mine_real_signals_and_outcomes()
            cls.save_history(hists)
            return hists
        except Exception as e:
            return existing
